### PR TITLE
change capital letters cuz it's annoying

### PR DESCRIPTION
**Pull request by maria-waffle**

### CODE REVIEW

**Comment by themonkeyhacker** [comment]
Fuck off :heart:

**Comment by maria-waffle** [comment]
:(

**Comment by themonkeyhacker** [comment]
take the L. Will merge bu

**Comment by themonkeyhacker** [comment]
Will merge but marking as invalid because you haven't sent pancake pics xoxo

**Comment by themonkeyhacker** [comment]
How does it feel to get merge pull req 69

**Comment by maria-waffle** [comment]
yay 69, but don't be shy take off invalid label ;) ❤️

**Comment by JamBot3000** [comment]
smh

**Comment by JamBot3000** [comment]
gonna add it back on the 7th day so it gets denied by hacktoberfest xoxoxo

**Pull request merged**
